%%En una empresa de Remis de nuestra ciudad, los móviles trabajan cubriendo los tres turnos del día. Los turnos son:
%%mañana, tarde y noche. Cada turno tiene definido un horario de inicio y un horario de fin.
%%Cada móvil está identificado con un número de móvil, y se cuenta con los datos del vehículo y número de patente de
%%remis. 
%%Cada móvil es manejado siempre por el mismo chofer, y dicho móvil trabaja en un único turno. Cada chofer tiene un
%%número de legajo y se mantienen sus datos personales. 
%%La Remisería trabaja con clientes fijos los cuales son empleados que pertenecen a empresas a las cuales se les presta
%%servicios (NO trabaja con pasajeros comunes). Por ello se mantienen los datos de la empresa: razón social, CUIT, condición
%%de IVA, ingresos brutos, domicilio, teléfono y fax; además se registran los datos personales de cada empleado perteneciente
%%a dicha empresa. 
%% Cuando un cliente (empleado) solicita un viaje, se registra el lugar de origen y el lugar de destino que informa el cliente
%%y se asigna y envía un móvil. Luego del recorrido, al cobrarle al cliente, el chofer le emite un ticket donde constan entre otros,
%%los siguientes datos: fecha, hora e importe. Esta información es comunicada por el chofer para que se registre completando
%%los datos del viaje y permitirá generar reportes para su respectivo control.

classDiagram
    class Turno {
        -String NombreTurno
        -Time HorarioInicio
        -Time HorarioFin
    }

    class Chofer {
        -int Legajo
        -String Nombre
        -String Apellido
        -String DNI
        -String Telefono
    }

    class Movil {
        -int NumeroMovil
        -String Marca
        -String Modelo
        -String Patente
    }

    class Empresa {
        -String RazonSocial
        -String CUIT
        -String CondicionIVA
        -String IngresosBrutos
        -String Domicilio
        -String Telefono
        -String Fax
    }

    class Empleado {
        -String Nombre
        -String Apellido
        -String DNI
        -String AreaSector
    }

    class Viaje {
        -String LugarOrigen
        -String LugarDestino
        -Date Fecha
        -Time Hora
        -double Importe
        +completarDatos()
        +emitirTicket()
    }

    Chofer "1" -- "1" Movil 
    Movil "*" --> "1" Turno 
    Empresa "1" *-- "1..*" Empleado 
    Empleado "1" --> "*" Viaje 
    Movil "1" --> "*" Viaje 