classDiagram

class Casa_venta_discos{
      +Discos_vendidos()
      +Generar_listado_ventas_mensual()
      +Generar_listado_alfabetico_interpretes()
      +Generar_factura(Venta.informacionVenta)
    }

class SelloDiscografico {
  +str nombre
  +str domicilio
  +str telefono
  +str email
}

class GeneroMusical {
  +str nombre
  +str descripcion
}

class Disco {
  +str nombreAlbum
  +int cantidadExistente
  +float precioUnitario
  +int anioEdicion
}

class Interprete {
  +str nombre
  +str apellido
  +str nacionalidad
}
class Venta{
  +string informacionVenta
}

SelloDiscografico "1" --> "0..*" Disco
GeneroMusical "1" --> "1..*" Disco 

Disco "1.." --> "1.." Interprete 
Casa_venta_discos  o-- Venta
Venta "1" --> "1..*" Disco
Casa_venta_discos "1" --> "1..*" Disco