classDiagram
    EAI -->"0..*" Reserva
    Reserva -->"1" Visita
    Reserva -->"1..*" CambioEstadoReserva
    CambioEstadoReserva -->"1" EstadoReserva
    Visita -->"1" Horario
    Visita -->"1" InstitucionEducativa
    InstitucionEducativa -->"1..*" Estudiante
    InstitucionEducativa -->"1..*" Docente
    Estudiante -->"1" NivelEducativo

    Visita -->"1" Recorrido
    Visita -->"1" Guia
    Guia -->"1" Estado
    Recorrido -->"1..*" Parada
    Parada -->"1" Area
    Recorrido -->"1" TipoRecorrido
    Area -->"1" Especie
    Especie -->"1" HabitadNatural
    Horario -->"1" EstadoHorario

    class EAI["EncargadoDeAtencionAInstituciones"] {

        - transferenciaRecibida()
        - setConfirmarReserva()
        - GenerarFacturaElectronica()
        - RegistrarHoraInicioReal()
        - finalizoElTiempoParaConfirmarReserva()
        - setAnularReserva() 
        - AsignarGuia()
    }
    class Visita {
        - Guia guiaDeVisita
        - NivelEducativo nivelEduEstudiantes
        - Recorrido recorridoARealizar
        - Reserva reservaRealizada
        - Horario horarioVisita
        - Docente[list] docentesQueParticipanDeLaVisita

        - iniciarVisita()
        - listarDocentes()
        + listarHorariosDisponibles()
        - definirObjetivo()
        - definirTipoRecorrido()
        + listarGuiasDisponibles()
        + ocuparHorario()
        + liberarHorario()
    }

    class Guia {
        - Str nombre
        - Estado estadoDeDisponibilidad

        + estaDisponible()
        - RegistrarHoraSalida()
        - EntregarManualActividades()
    }
    class Estado {
        - Str nombre
        - Str descripcion

        - esDisponible()
    }

    class Horario {
        - Time horaInicioEstimado
        - Time horaFin
        - EstadoHorario Estado
        + estaDisponible()
        + ocuparHorario()
        + liberarHorario()
    }

    class EstadoHorario{
        - Str nombre
        - Str descripcion

        + esDisponible()
    }
    class Reserva{
        - InstitucionEducativa Insitucion

        - Horario fechaHoraDeRecorrido
        - Int cantidadVisitantesPrevista
        - NivelEducativo NivelEducativoDeAlumnos
        - Date diaDeVisita

        - DiaEsValido()
        - horarioEstaDisponible()
        - calcularTotal()

        - setAgendarReserva()
        - enviarEmail()
        - ocuparHorario()
        + setConfirmarReserva()
        + Pasaron96HorasDesdeAgendarReserva()
        + setAnularReserva()
        - liberarHorario()

        + listarGuiasDisponiblesElDiaDeVisita()
    }
    class InstitucionEducativa {
        - Str nombre
        - Str domicilio
        - Str telefono
        - Email email
        - Estudiante[list] listaEstudiantes
        - Docente[list] listaDocentes

        +listarDocentesQueVanALaVIsita()
    }

    class Estudiante {
        - Str nombre
        - NivelEducativo nivelEducativo
    }
    class Docente {
        - Str nombre
        - Str asignatura

        + vaALaVisita()
    }

    class NivelEducativo {
        - Str nombre
        - Str descripcion
    }
    class Recorrido {
        - Int cupo
        - Float precioPorPersona
        - Int duracionTotal
        + listarTiposRecorrido()
    }
    class TipoRecorrido {
        - Str nombre
        - Str descripcion
        + getTipoRecorrido()
    }

    class Parada {
        - Int numeroParada
        - Area areaParada
    }
    class Area {
        - Especie especieAlbergada
        - Str codigoQR
    }
    class Especie {
        - Str nombre
        - HabitadNatural habitadNaturalDeEspecie
    }
    class HabitadNatural {
        - Str nombre
        - Str descripcion
    }

    class CambioEstadoReserva {
        - EstadoReserva estado
        - DateTime FechaHoraInicio
        - DateTime FechaHoraFin

        + setAgendarReserva()
        + setConfirmarReserva()
        + Pasaron96HorasDesdeAgendarReserva()
        + setAnularReserva()
    }

    class EstadoReserva {
        - str nombre
        - str descripcion

        + esAsignada()
        + esConfirmada()
        + esAnulada()
    }