%%Una cadena de Supermercado de atención permanente de 24 hs. de esta ciudad tiene varias sucursales identificadas con
%%un número, teléfono y dirección. En cada sucursal trabajan distintos cajeros en diferentes turnos. Un cajero solo trabaja en
%%una sucursal y en un solo turno por día (mañana, tarde o noche). 
%% Cada sucursal tiene una cantidad de cajas para tickear y cobrar los productos que adquiere cada cliente. Cada caja es
%%identificada por un número y tiene un estado: abierta o cerrada.
%% El responsable de cajas de cada sucursal, va asignando cajeros a alguna caja según la demanda y necesidades de cobros
%%a los clientes. Durante todo el día los cajeros van rotando entre distintas cajas según la asignación indicada por dicho
%%responsable y no necesariamente siempre atiende las mismas cajas.
%%Cuando un cajero es asignado a una caja, la caja se considera abierta, y se registra la fecha y hora desde la cual se realiza
%%la apertura. El cajero pasa los artículos que adquiere un cliente, para ello los artículos se marcan cuando el sensor lee su
%%código de identificación, y el cajero sólo indica en el teclado la cantidad de cada artículo; por cada venta se genera, registra
%%e imprime un Ticket para dicho cliente, conteniendo el detalle de los artículos comprados. Los artículos están identificados
%%por un código y un nombre. 
%%En un ticket, además de la lista de artículos, el precio unitario, la cantidad y el importe total del ticket, consta el número
%%de sucursal, el número de caja, la identificación del cajero, la fecha y la hora de emisión. Por cada venta se actualiza el stock
%%de los artículos disponibles.

classDiagram
    class Sucursal {
        -int Numero
        -String Telefono
        -String Direccion
    }

    class Cajero {
        -String Identificacion
        -String Nombre
        -String Turno
    }

    class Caja {
        -int Numero
        -String Estado
    }

    class AsignacionCaja {
        -Date FechaYHoraApertura
        -Date FechaYHoraCierre
    }

    class Ticket {
        -int NumeroTicket
        -Date FechaEmision
        -Time HoraEmision
        -double ImporteTotal
    }

    class DetalleTicket {
        -int Cantidad
        -double PrecioUnitario
        -double Subtotal
    }

    class Articulo {
        -String CodigoIdentificacion
        -String Nombre
        -double PrecioActual
        -int StockDisponible
        +actualizarStock(int cantidad)
    }

    Sucursal "1" --> "1..*" Caja 
    Sucursal "1" --> "1..*" Cajero 
    Cajero "1" --> "0..*" AsignacionCaja 
    Caja "1" --> "0..*" AsignacionCaja 
    AsignacionCaja "1" --> "0..*" Ticket 
    Ticket "1" *-- "1..*" DetalleTicket 
    DetalleTicket "*" --> "1" Articulo